### ISSUE TITLE
Support for pydantic v2

### ISSUE THREAD

**Issue by max-radin** [amazon-braket/amazon-braket-schemas-python#161]
**Describe the feature you'd like**
Support for at least one `2.X.X` version of pydantic.

**How would this feature be used? Please describe.**
Adding support for [pydantic v2](https://docs.pydantic.dev/2.0/blog/pydantic-v2-final/) would allow us to upgrade [orquestra-sdk](https://github.com/zapatacomputing/orquestra-sdk) to also use pydantic v2 and benefit from the improvements it offers. 

The reason for this is that the [orquestra-core metapackage](https://github.com/zapatacomputing/orquestra-core) depends on pydantic transitively through orquestra-sdk as well as amazon-braket-default-simulator and amazon-braket-schemas-python. So currently, upgrading orquestra-sdk to pydantic v2 would create a dependency conflict for orquestra-core.

**Describe alternatives you've considered**
Our current strategy is to continue using `pydantic < 2.0.0`.

**Comment by guomanmin** [comment]
Hi @max-radin - thanks for raising this, we're looking at a couple of options before getting back.

**Comment by speller26** [comment]
Hello! We're not going to pursue this upgrade for the time being, but feel free to leave the issue open so we may revisit it in the future.

**Comment by tachikoma-li** [comment]
Just to echo the comments above, it would be great that braket could support Pydantic 2. It seems https://github.com/amazon-braket/amazon-braket-schemas-python/pull/163 has already done the work by changing the import from `pydantic.v1`, as recommend by the official [doc](https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features) if we don't want to spend too much to fully migrate to 2.0.

**Comment by math411** [comment]
Hello all,

The team is currently exploring options to make these upgrades, we will post more information in this thread when we have an update.

**Comment by math411** [comment]
After discussing internally, we have planned to complete this upgrade in Q1.

**Comment by richrines1** [comment]
hi, by any chance is there a timeline for this? it will soon be a blocker for us

thanks :)

**Comment by vanyae-cqc** [comment]
Unfortunately we've had to drop support for Braket in our stack until it can support Pydantic V2. Thanks for taking a look at this and look forward to supporting Braket again soon 🙏

**Comment by math411** [comment]
Hey All,

Thank you for your patience with us! The fix for Pydantic 2.x has been released for the schemas repository. Amazon Braket is continuously looking to prioritize bug fixes and develop mechanisms to address issues as they arise. 

Internally, we are developing an approach to get better tracking of open-source issues. Reach out with any additional questions or open a new issue for additional feature requests and support.

**Comment by richrines1** [comment]
tysm @math411!!

**Comment by vanyae-cqc** [comment]
Thank you @math411 and team! We will immediately start working to support Braket again ASAP
